token:
  expiration_time: 864000000 
  secret: '{cipher}AQCnJSA0+DO29OBZNdxm3jzC759d3DVXET82NGNoPJTDBtD0g/EuU7+kbvNXxqN/HstZICxhl2H085VcqaahYYNRCB97w9efxOwmujSvSaqJRAf/WRf5KmSOPP5RC+FMGxutiLvWCNi2BQ/FPR5e6Eo7vaHxwKfZCwvkQLV/zHoQmSZo0U5A8VnBKFHdfM71s18dsdAuNg7O6pL35Z6oQ/dbUYV+rQltF0Ve/yVE/LYUoyz2qxkQ7dCd1tRVNoMqqUFu38nz2kaa5bTDnShEtdbhMiGyB40GnOtGUm334noZYgOMflbJWwwB+aNQj85abXjI1Dz5r7Nl65w6o+l8nuOMWLST1LNDMBePoBH88pQibMDFyxogj57rDOFm/HErV18='

gateway:
  ip: 172.18.0.5

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:microservice
    username: sa
    password: '{cipher}AQAsfbbeulzk6wpUwGBbLNH1Y/GMNARdAZIQRR09dK9Lekhj8Ex1cdaAgT+TWyuYcx+RB8uv2qCTeeoxjYy4AU+pCJhIB+DRiTkBY6i6hCLehTYrJMfa0L8THx80MfDkfspXwKDMF3RhAc/ShEk6I17nDEMrdAOZcY4u6RCfBSp/0EgXKD2eTAnOL9GXpyhP4wuCiCnrYUsZYti+jqP9+81ZnK0qAEJNkoiUQbbuQvd+3DDJIF890E9u24DVNKpPcEjhB2gJCCqWopG6eNd5IhWWsmoifx8uTArEWcJkyDl8MP6PeLVHCYf8snNX/jtLFsl+rMHMd6BYmkv4qp3O/mxdn6jkAjmURjKCgjgm5tzhu5+aG8oUuCHTOiw14oRf9xQ='

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no Orders.
