token:
  expiration_time: 864000000 
  secret: '{cipher}AQAGK5JwLyuuZ1pB7CbgQ8XwGvFjDhWDFcxKyqzlzh1j/Ypzl8ETxy2PNvsmJG4KhgyUjmsOAMVoNVWee8lXgiq8q2ElC8lPtPdjtx7qooBUahg9jUo3RNZdfCfpFvCLKiCppSV+3GmQhqV6SSLrQuimQezEft3Zicp+oLdALywrEinaU1xYoSOsavKum+UwK6tl3PBzRGpYPaniR717GuDwfm0o9z1PG6y2xB+Mlr5UomgAihp3V8i0U7zVWLyXkIAncJJbjY11nIeLYe0NbKXELuEs955/doSWrihvWz3C7hwC7o8Up5fd4BnNssnB9zOjRh//Z9Buu7xwgfB14ng7zSnJnuoy7A8DkHt4wYHWKTzlINfw0dPf1/4fnBCG98f22ckmxn/lsDk9nOEveHpL'

gateway:
  ip: 172.18.0.5

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:microservice
    username: sa
    password: '{cipher}AQAsfbbeulzk6wpUwGBbLNH1Y/GMNARdAZIQRR09dK9Lekhj8Ex1cdaAgT+TWyuYcx+RB8uv2qCTeeoxjYy4AU+pCJhIB+DRiTkBY6i6hCLehTYrJMfa0L8THx80MfDkfspXwKDMF3RhAc/ShEk6I17nDEMrdAOZcY4u6RCfBSp/0EgXKD2eTAnOL9GXpyhP4wuCiCnrYUsZYti+jqP9+81ZnK0qAEJNkoiUQbbuQvd+3DDJIF890E9u24DVNKpPcEjhB2gJCCqWopG6eNd5IhWWsmoifx8uTArEWcJkyDl8MP6PeLVHCYf8snNX/jtLFsl+rMHMd6BYmkv4qp3O/mxdn6jkAjmURjKCgjgm5tzhu5+aG8oUuCHTOiw14oRf9xQ='

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no Orders.
